### ISSUE TITLE
pip does not reflect the most recent version

### ISSUE THREAD

**Issue by metllord** [wharton/sasdataframe#1]
PIP is installing 0.0.5 and the newest version is 0.0.6

**Comment by FlipperPA** [comment]
0.0.6 just needs to be uploaded (or unhidden) on PyPI: https://pypi.python.org/pypi/sasdataframe/

**Comment by joedougherty** [comment]
@metllord Thanks for pointing this out! sasdataframe 0.0.6 now available via PyPI.
